app/models/post.py
from app.extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), unique=True, nullable=False)
    content = db.Column(db.Text, nullable=False)
    author = db.Column(db.String(80), unique=True, nullable=False)

app/models/question.py
from app.extensions import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    answer = db.Column(db.Text, nullable=False)

app/models/result.py
from app.extensions import db


class Result(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Real_result = db.Column(db.Float)
    PL_regression = db.Column(db.Float)
    Gradient_boosting = db.Column(db.Float)
    RNN = db.Column(db.Float)

    def __init__(self, Real_result, PL_regression, Gradient_boosting, RNN):
        self.Real_result = Real_result
        self.PL_regression = PL_regression
        self.Gradient_boosting = Gradient_boosting
        self.RNN = RNN

app/models/user.py
from app.extensions import db


class user(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def _init_(self, username, password, email):
        self.username = username
        self.password = password
        self.email=email

app/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class LoginForm(FlaskForm):
    email = StringField("Email: ", validators=[Email("Некорректный email")])
    psw = PasswordField("Пароль: ", validators=[DataRequired(),
                                                Length(min=4, max=100, message="Пароль должен быть от 4 до 100 символов")])
    remember = BooleanField("Запомнить", default = False)
    submit = SubmitField("Войти")

class RegisterForm(FlaskForm):
    name = StringField("Имя: ", validators=[Length(min=4, max=100, message="Имя должно быть от 4 до 100 символов")])
    email = StringField("Email: ", validators=[Email("Некорректный email")])
    psw = PasswordField("Пароль: ", validators=[DataRequired(),
                                                Length(min=4, max=100, message="Пароль должен быть от 4 до 100 символов")])

    psw2 = PasswordField("Повтор пароля: ", validators=[DataRequired(), EqualTo('psw', message="Пароли не совпадают")])
    submit = SubmitField("Регистрация")

app/__init__.py
from flask import Flask
from config import Config
from app.extensions import db
from app.extensions import bcrypt


def create_app(config_class=Config):
    app = Flask(__name__)
    app.secret_key = 'qwe'
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.page import bp as page_bp
    app.register_blueprint(page_bp, url_prefix='/page')

    from app.posts import bp as posts_bp
    app.register_blueprint(posts_bp, url_prefix='/posts')

    from app.questions import bp as questions_bp
    app.register_blueprint(questions_bp, url_prefix='/questions')

    from app.register import bp as register_bp
    app.register_blueprint(register_bp, url_prefix='/register')

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    @app.route('/test')
    def test_page():
        return '<h1>Hello World</h1>'

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash

from app.extensions import db
from app.main import bp


@bp.route('/')
def index():
    return render_template("index.html")

app/page/__init__.py
from flask import Blueprint

bp = Blueprint('page', __name__)

from app.page import routes

app/page/routes.py
import keras
from flask import render_template, request
from app.page import bp
from app.page.Build_Model_Regression import preprocessing, training_rgr, read_data
import pickle
import pandas as pd
from app.page.db_process import db_process
from app.models.result import Result


@bp.route('/', methods=['GET', 'POST'])
def index():
    return render_template("page/index.html")


@bp.route('/training', methods=['GET', 'POST'])
def training():
    if request.method == "POST":
        metrics = training_rgr()
        sms_rgr = "Training model regression complete!!!"
        sms_bst = "Training model gradient regression complete!!!"
        sms_rnn = "Training model recurrent neural network complete!!!"
        text_out = [sms_rgr, sms_bst, sms_rnn]
        return render_template("page/index.html", text_out=text_out, metrics=metrics)
    return render_template("page/index.html")


@bp.route('/testing', methods=['GET', 'POST'])
def testing():
    if request.method == "POST":
        x_test, y_test = read_data('static/Data_testing.csv')
        poly_features = preprocessing(x_test)

        model_rgr = pickle.load(open("static/polymodel.pkl", "rb"))
        y_pred_rgr = model_rgr.predict(poly_features)  # the result of the prediction by using regression

        model_bst = pickle.load(open("static/gb_model.pkl", "rb"))
        y_pred_bst = model_bst.predict(poly_features)

        model_rnn = keras.models.load_model("static/rnn_model.h5")
        y_pred_rnn = model_rnn.predict(x_test).flatten()

        # save data to sql
        db_process(y_test, y_pred_rgr, y_pred_bst, y_pred_rnn)
        # message save data successfully
        mss = "# Save data successfully"
        return render_template("page/index.html", mss=mss)
    return render_template("page/index.html")


@bp.route('/result', methods=['GET', 'POST'])
def result():
    if request.method == "POST":
        results = Result.query.all()  # the query all data in the table
        return render_template("page/index.html", results=results)
    return render_template("page/index.html")

app/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)

from app.posts import routes

app/posts/routes.py
from flask import render_template

from app import page
from app.posts import bp
from app.models.post import Post


@bp.route('/<int:page_num>')
def index(page_num):
    posts = Post.query.paginate(per_page=3, page=page_num)
    return render_template("posts/index.html", posts=posts)

app/questions/__init__.py
from flask import Blueprint

bp = Blueprint('questions', __name__)

from app.questions import routes

app/questions/routes.py
from flask import render_template, request, url_for, redirect

from app.extensions import db
from app.questions import bp
from app.models.question import Question

@bp.route('/', methods=['GET', 'POST'])
def index():
    questions = Question.query.all()

    if request.method == 'POST':
        new_question = Question(content=request.form['content'],
                                answer=request.form['answer'])
        db.session.add(new_question)
        db.session.commit()
        return redirect(url_for('questions.index'))

    return render_template("questions/index.html", questions=questions)

app/register/__init__.py
from flask import Blueprint

bp = Blueprint('register', __name__)

from app.register import routes

app/register/routes.py
from flask import render_template, request, url_for, redirect, flash
from app.extensions import db
from app.extensions import bcrypt
from app.register import bp
from app.forms.forms import RegisterForm, LoginForm
from app.models.user import user
from werkzeug.security import generate_password_hash, check_password_hash



@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if (len(request.form['username']) > 4) and (len(request.form['password1']) > 4) and (
                request.form['password1'] == request.form['password2']):
            hash = bcrypt.generate_password_hash(request.form['password1']).decode('utf-8')
            new_user = user(username=request.form['username'],
                            password=hash,
                            email=request.form['email'])
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('register.index'))
        else:
            flash("Неверно заполнены поля", 'error')
    return render_template("register/index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Мой блог</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
</head>
<body style="background: linear-gradient(90deg, rgb(83,163,223) 0%, rgb(156,156,255) 50%, rgb(88,159,216) 100%); background-size: cover;">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Навигация</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.index', page_num=1) }}">Посты</a>
                </li>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    Разделы блога
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('page.index') }}">Статичная страница</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('questions.index') }}">Вопросы автору</a></li>
                </ul>
            </ul>
            <form class="d-flex">
                <li class="nav-item">
                    <div id="google_translate_element"></div>
                    <script type="text/javascript">
                        function googleTranslateElementInit() {
                            new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
                        }
                    </script>
                    <script type="text/javascript"
                            src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
                </li>
                <li>
                    {% if 'username' in session %}
                        <li class="last" style="color:#fff">{{ session['username'] }}<a
                                href="{{ url_for('auth.logout') }}">
                            <button type="button" class="btn btn-primary">Выйти</button>
                        </a></li>
                    {% else %}
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#reg1">Регистрация
                        </button>
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#log1">Авторизация
                        </button>
                    {% endif %}
                </li>
            </form>
        </div>
    </div>
</nav>

{% include 'register/index.html' %}
{% include 'auth/index.html' %}
<div class="content">
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script>
        (function () {
            'use strict';

            // Получите все формы, к которым мы хотим применить пользовательские стили проверки Bootstrap
            var forms = document.querySelectorAll('.needs-validation');

            // Зацикливайтесь на них и предотвращайте отправку
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        // Получаем значения полей пароля и подтверждения пароля
                        var password = form.querySelector('#password1').value;
                        var confirm_password = form.querySelector('#password2').value;
                        var passwordHelpBlock = form.querySelector('#passwordHelpBlock');

                        // Проверяем совпадение паролей
                        if (password !== confirm_password) {
                            passwordHelpBlock.classList.remove('d-none');
                            form.classList.remove('was-validated');
                            event.preventDefault();
                            event.stopPropagation();
                        } else {
                            passwordHelpBlock.classList.add('d-none');
                            if (!form.checkValidity()) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }
                    }, false);
                });
        })();
    </script>

</div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title">
        <h1>{% block title %}Главная страница{% endblock  %}</h1>
    </span>
{% endblock %}

app/templates/page/index.html
{% extends "base.html" %}
{% block content %}
    <br><br>
    <div class="container shadow p-3 mb-5 bg-body rounded">
    <span>Мы решаем задачу прогнозирования цен на жилье тремя методами: полиномиальная регрессия, градиентный бустинг, рекуррентная нейронная сеть <br>
        Данные получаем с kaggle.com (https://www.kaggle.com/code/aminizahra/polynomial-reгрессия).<br>
        Наш интерфейс разделен на 3 части:<br>
        Часть 01: используется для обучения моделей со следующими шагами:<br>
         - шаг 01: загрузите данные из файла в статическую папку.<br>
         - шаг 02: Обучите модели с приведенными выше данными, соответствующими указанным выше алгоритмам.<br>
         - шаг 03: После обучения сохраняем модели в файлы 03, соответствующие алгоритмам 03: polymodel.pkl (полиномиальная регрессия),
         gb_model.pkl (повышение градиента), rnn_model.h5 (рекуррентная нейронная сеть).<br>
        Часть 02: используйте доступные модели и файлы тестовых данных для тестирования<br>
        Часть 03: прогнозные данные сохраняются в базе данных, данные выводятся на экран.<br>

    </span>
    </div>
    <div class="container shadow p-3 mb-5 bg-body rounded">
        <form action="{{ url_for('page.training') }}" method="post">
            <ol>
                <li>Полиномиальная регрессия</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[0] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[0][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[0][1] }}</span>
                {% endif %}
                <li>Градиентный бустинг</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[1] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[1][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[1][1] }}</span>
                {% endif %}
                <li>Рекуррентная нейронная сеть</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[2] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[2][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[2][1] }}</span>
                {% endif %}
            </ol>
            <button type="submit" class="btn btn-primary">Построить модель (Обучение)</button>
        </form>
    </div>
    <div class="container shadow p-3 mb-5 bg-body rounded">
        <span>Пожалуйста, если хотите проверить данные, нажмите кнопку ниже!</span>
        <form action="{{ url_for('page.testing') }}" method="post">
            {% if mss %}
                <h5>{{ mss }}</h5>
            {% endif %}
            <button type="submit" class="btn btn-primary" name="testing">Тестирование модели</button>
        </form>
    </div>

    <div class="container shadow p-3 mb-5 bg-body rounded">
        <form action="{{ url_for('page.result') }}" method="post">
            <button type="submit" class="btn btn-primary">Показать результат прогноза</button>
            {% if results %}
                <div class="overflow-auto">
                    <table class="table table-sm">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Real price</th>
                            <th scope="col">Price_regression</th>
                            <th scope="col">Price_Gradient Boosting</th>
                            <th scope="col">Price_RNN</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for r in results %}
                            <tr>
                                <td>{{ r.id }}</td>
                                <td>{{ r.Real_result }}</td>
                                <td>{{ r.PL_regression }}</td>
                                <td>{{ r.Gradient_boosting }}</td>
                                <td>{{ r.RNN }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </form>
    </div>

{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title">
        <h1>{% block title %}Посты{% endblock %}</h1>
    </span>
    {% for post in posts %}
        <div style="margin-top: 1%">
            <div class="container-fluid">
                <div class="row align-items-start">
                    <div class="col">
                        <div class="bg-image card shadow-1-strong"
                             style="background: radial-gradient(circle, rgb(134,145,214) 0%, rgb(72,181,236) 100%); background-size: 100%">

                            <div class="card-body text-black">
                                <h2>{{ post.title }}</h2>
                                <p>Автор поста: <b>{{ post.author }}</b></p>
                                <p>{{ post.content }}</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if posts.pages %}
        <p>
        <ul class="pagination justify-content-center">
            {% if posts.has_prev %}
                <li class="page-item"><a class="page-link" href="{{ url_for('posts.index', page_num=posts.prev_num) }}">Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">Предыдущая</span>
            {% endif %}

            {% for p in posts.iter_pages(left_edge=2, right_edge=2) %}
                {% if p %}
                    <li class="page-item"><a class="page-link"
                                             href="{{ url_for('posts.index', page_num=p) }}">{{ p }}</a></li>
                {% else %}
                    <li class="page-item disabled" id="example_ellipsis"><a href="#">...</a></li>
                {% endif %}
            {% endfor %}

            {% if posts.has_next %}
                <li class="page-item"><a class="page-link" href="{{ url_for('posts.index', page_num=posts.next_num) }}">Следующая</a>
                </li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">Следующая</span>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

app/templates/questions/index.html
{% extends 'base.html' %}
{% block content %}
    <span class="title">
        <h1>{% block title %}FAQ{% endblock  %}</h1>
    </span>
    <div style="text-align: center;">
    <form method="POST">
        <p>
            <textarea id="content"
                      name="content"
                      placeholder="Вопрос"
                      cols="30" rows="3">
            </textarea>
        </p>
        <p>
            <textarea id="answer"
                      name="answer"
                      placeholder="Ответ"
                      cols="30" rows="3">
            </textarea>
        </p>
        <p><input class="btn btn-primary" type="submit" value="Отправить"></p>
    </form>
    {% for q in questions %}
        <hr>
    <h4>Вопрос: {{ q.content }}</h4>
    <h4>Ответ: {{ q.answer }}</h4>
        <hr>
    {% endfor %}
    </div>
{% endblock %}

app/templates/register/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Блог ленивца</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<div class="modal"  tabindex="-1" role="dialog" id="reg1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Регистрация</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="row g-3 needs-validation"  action="{{ url_for('register.index') }}" method="post"
                  id="registrationForm" novalidate>
                <div class="modal-body">

                    <div class="col-md-4">
                        <label for="validationCustom01" class="form-label">Имя: </label>
                        <input type="text" class="form-control" name="username" required>
                        <div class="invalid-feedback">
                            Пожалуйста, выберите имя пользователя.
                        </div>
                    </div>

                    <div class="col-md-4">
                        <label for="validationCustom02" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password1" name="password1" required>
                        <div class="invalid-feedback">
                            Пожалуйста, введите пароль.
                        </div>
                    </div>

                    <div class="col-md-4">
                        <label for="validationCustom03" class="form-label">Повтор пароля: </label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                        <div class="invalid-feedback">Подтвердите пароль.</div>
                        <div id="passwordHelpBlock" class="form-text text-danger d-none">Пароли не совпадают</div>
                    </div>

                    <div class="col-md-4">
                        <label for="validationCustom04" class="form-label">Email: </label>
                        <input type="text" class="form-control" name="email" required>
                        <div class="invalid-feedback">
                            Пожалуйста, введите вашу почту.
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
</body>